const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),E=require('./dist/engine.js');
new vm.Script(fs.readFileSync('dist/planner.js','utf8'));
const ctx={structuredClone,CalendarEngine:E};vm.runInNewContext(fs.readFileSync('dist/teacher-data.js','utf8'),ctx);
const app=fs.readFileSync('dist/app.js','utf8'),features=fs.readFileSync('dist/features.js','utf8');
vm.runInNewContext(app.slice(0,app.indexOf('let state='))+features.slice(features.indexOf('const uid='),features.indexOf('let book;'))+';globalThis.checkData=validate;',ctx);
const d=structuredClone(ctx.TeacherPreset.data),original=structuredClone(d);
const source=E.lessons('2026-10-05','all',d).find(l=>!l.inquiry),target=E.lessons('2026-10-06','all',d).find(l=>!l.inquiry);
d.lessonChanges=[{id:'move1',type:'move',classId:source.classId,source, date:target.date,time:target.time,replaced:[target.key],reason:'校務調整'}];
assert(ctx.checkData(d));assert(!E.lessons(source.date,'all',d,true).some(l=>l.key===source.key));assert(!E.lessons(target.date,'all',d).some(l=>l.key===target.key));
assert(E.lessons(target.date,source.classId,d).some(l=>l.key==='change_move1'));
assert.deepEqual(E.lessons('2026-10-12','all',d),E.lessons('2026-10-12','all',original));
const moved=E.lessons(target.date,source.classId,d).find(l=>l.key==='change_move1');
d.lessonChanges.push({id:'delete1',type:'delete',classId:source.classId,source:moved,replaced:[],reason:''});assert(!E.lessons(target.date,'all',d).some(l=>l.key===moved.key));
d.lessonChanges.pop();assert(E.lessons(target.date,'all',d).some(l=>l.key===moved.key));d.lessonChanges.pop();assert.deepEqual(E.lessons(source.date,'all',d),E.lessons(source.date,'all',original));
d.lessonChanges.push({id:'extra1',type:'extra',classId:source.classId,date:'2026-10-10',time:'08:10',replaced:[],reason:''});assert.equal(E.lessons('2026-10-10',source.classId,d).length,1);
const before=E.remaining(source.classId,0,original,{date:'2026-10-02',time:'23:59'}).total;assert.equal(E.remaining(source.classId,0,d,{date:'2026-10-02',time:'23:59'}).total,before+1);
assert.equal(E.feedbackWeek('2026-10-02'),'2026-09-26');assert.equal(E.feedbackWeek('2026-10-03'),'2026-10-03');assert.equal(E.feedbackWeek('2027-01-01'),'2026-12-26');
d.feedback={'2026-09-26':{grade1:'高一回饋',grade2:'高二回饋',updatedAt:new Date().toISOString()}};assert(ctx.checkData(d));assert(ctx.checkData(JSON.parse(JSON.stringify(d))));assert.equal(d.feedback[E.feedbackWeek('2026-10-03')],undefined);assert.equal(d.feedback['2026-09-26'].grade1,'高一回饋');
const bad=structuredClone(d);bad.feedback['2026-09-26'].grade1='x'.repeat(12001);assert(!ctx.checkData(bad));bad.feedback=d.feedback;bad.lessonChanges[0].date='2028-01-01';assert(!ctx.checkData(bad));
console.log('PASS: date-scoped move/replacement/delete/undo, holiday makeup and counts, next-week isolation, Saturday/year rollover, backup validation');
