const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),E=require('./dist/engine.js');
const ctx={};vm.runInNewContext(fs.readFileSync(__dirname+'/dist/teacher-data.js','utf8'),ctx);const d=JSON.parse(JSON.stringify(ctx.TeacherPreset.data));
assert.equal(d.classes.filter(c=>c.mode==='exam').length,8);
assert.equal(d.classes.filter(c=>c.mode==='exam').reduce((n,c)=>n+c.slots.length,0),16);
assert.equal(d.classes.filter(c=>c.mode==='inquiry').reduce((n,c)=>n+c.slots.length,0),4);
assert.deepEqual(d.exams.map(e=>[e.date,e.end]),[['2026-10-13','2026-10-14'],['2026-12-02','2026-12-03'],['2027-01-18','2027-01-19']]);
assert.equal(E.lessons('2026-12-24','wz-p103',d).length,0);
assert.equal(E.lessons('2026-12-24','wz-p214',d).length,1);
assert.equal(E.lessons('2026-09-17','wz-p103',d).length,0);
assert.equal(E.lessons('2026-09-17','wz-p214',d).length,1);
assert.equal(E.lessons('2026-11-06','all',d).length,0);
assert.equal(E.lessons('2026-11-09','all',d).length,0);
assert.equal(E.lessons('2026-10-16','wz-p107',d).length,1);
const counts=d.classes.filter(c=>c.mode==='exam').map(c=>E.remaining(c.id,0,d,{date:'2026-09-30',time:'23:00'}).total);
assert.deepEqual(counts,[3,3,3,2,3,3,3,4]);
console.log('PASS: actual teacher schedule and exam dates, grade-specific closures, partial-day exclusion, sports and makeup, countdowns',counts);

assert.equal(d.classes.filter(c=>c.subject==='基礎物理').length,4);
assert.equal(d.classes.filter(c=>c.subject==='選修物理').length,4);
assert.deepEqual(d.classes.find(c=>c.id==='wz-p210').slots,[{day:2,time:'09:10'},{day:4,time:'09:10'}]);
assert.equal(d.classes.some(c=>c.id==='wz-i210'),false);
ctx.structuredClone=structuredClone;
const old=structuredClone(d);delete old.scheduleRevision;
for(const c of old.classes)if(c.id.startsWith('wz-p2'))c.subject='基礎物理';
old.classes.find(c=>c.id==='wz-p210').slots=[{day:2,time:'09:10'}];
old.classes.push({id:'wz-i210',name:'高二 210',mode:'inquiry',subject:'自然探究與實作',slots:[{day:4,time:'09:10'}],target:0});
const clean={id:ctx.TeacherPreset.id,data:structuredClone(old)};
assert.equal(ctx.correctTeacherSchedule(clean),true);
assert.equal(clean.data.classes.some(c=>c.id==='wz-i210'),false);
assert.equal(ctx.correctTeacherSchedule(clean),false);
const recorded={id:ctx.TeacherPreset.id,data:structuredClone(old)};
recorded.data.notes.keep={classId:'wz-p210',content:'保留進度'};
recorded.data.sessions.push({id:'existing',classId:'wz-i210',memo:'換課紀錄'});
const before=JSON.stringify([recorded.data.notes,recorded.data.sessions,recorded.data.events]);
ctx.correctTeacherSchedule(recorded);
assert.equal(JSON.stringify([recorded.data.notes,recorded.data.sessions,recorded.data.events]),before);
assert.equal(recorded.data.classes.find(c=>c.id==='wz-i210').historicalSchedule,true);
assert.equal(recorded.data.scheduleCorrections[0].previousClasses.length,11);
const other={id:'another-teacher',data:structuredClone(old)};
assert.equal(ctx.correctTeacherSchedule(other),false);
assert.deepEqual(other.data,old);
for(const file of ['teacher-data.js','school.js'])new vm.Script(fs.readFileSync(__dirname+'/dist/'+file,'utf8'));
console.log('PASS: corrected subjects, Thursday 210, one-time migration, records preserved, other workspaces unchanged');
