const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const E=require('./dist/engine.js');
for(const file of ['engine.js','storage.js','app.js','features.js','sw.js'])new vm.Script(fs.readFileSync(__dirname+'/dist/'+file,'utf8'));
const base={termStart:'2026-09-01',termEnd:'2027-01-22',classes:[{id:'c1',mode:'exam',slots:[{day:1,time:'09:00'},{day:3,time:'09:00'},{day:5,time:'09:00'}]},{id:'inq',mode:'inquiry',slots:[],target:10,inquiryMethod:'target'}],exams:[{date:'2026-10-14',end:'2026-10-15'},{date:'2026-11-25',end:'2026-11-26'},{date:'2027-01-13',end:'2027-01-14'}],events:[],sessions:[]};
const at={date:'2026-09-30',time:'19:00'};
assert.deepEqual(E.period(base,1),{start:'2026-10-16',end:'2026-11-25'});
assert.deepEqual(E.period(base,2),{start:'2026-11-27',end:'2027-01-13'});
assert.equal(E.remaining('c1',0,base,at).total,5);
assert.equal(E.remaining('c1',1,base,at).total,17);
assert.equal(E.remaining('c1',2,base,at).total,20);
assert.equal(E.remaining('c1',1,base,{date:'2026-11-23',time:'09:00'}).total,0);
assert.equal(E.remaining('c1',1,base,{date:'2026-11-23',time:'08:59'}).total,1);
assert.equal(E.remaining('c1',1,base,{date:'2026-11-25',time:'00:00'}).total,0);
base.events.push({id:'a',date:'2026-10-16',classId:'all',type:'off'},{id:'b',date:'2026-10-16',classId:'c1',type:'off'});
assert.equal(E.remaining('c1',1,base,at).total,16);
assert.equal(E.remaining('c1',1,base,at).excluded,1);
base.events.push({id:'e',date:'2026-10-16',classId:'c1',type:'extra',time:'11:00'});
assert.equal(E.remaining('c1',1,base,at).total,17);
assert.equal(E.lessons('2027-02-01','all',base).length,0);
base.sessions=[{id:'s1',classId:'inq',date:'2026-09-29',time:'09:00',done:true,minutes:50},{id:'s2',classId:'inq',date:'2026-09-30',time:'09:00',done:false,minutes:50},{id:'s3',classId:'inq',date:'2026-10-14',time:'09:00',done:false,minutes:100}];
assert.deepEqual(E.inquiry('inq',base,at),{done:1,future:1,unconfirmed:1,target:10,total:9,minutes:50});
assert.equal(E.lessons('2026-10-14','inq',base).length,1);
base.classes[1].inquiryMethod='scheduled';assert.equal(E.inquiry('inq',base,at).total,1);
assert.deepEqual(E.parseCSV('\ufeff班級,科目\r\n101,"自然,探究"\r\n'),[{'班級':'101','科目':'自然,探究'}]);
assert.throws(()=>E.parseCSV('a,b\n1'));
assert.throws(()=>E.parseCSV('a,b\n1,"open'));
assert.equal(E.addDays('2026-12-31',1),'2027-01-01');
console.log('PASS: script syntax; three exam periods; elapsed lesson boundaries; duplicate closures; makeup; term end; inquiry completion, duration, scheduled count and exam independence; CSV quoting/errors; year boundary.');
const app=fs.readFileSync(__dirname+'/dist/app.js','utf8'),features=fs.readFileSync(__dirname+'/dist/features.js','utf8');
const migrationAndValidation=app.slice(0,app.indexOf('let state='))+features.slice(features.indexOf('const uid='),features.indexOf('let book;'));
const importParser=features.slice(features.indexOf('function parseImport('),features.indexOf('async function upload('));
vm.runInNewContext(migrationAndValidation+`let state=migrate(defaults);`+importParser+`
assert.equal(validate(state),true);
state.notes.example={date:'2026-09-30',classId:'c1',time:'10:10',content:'keep',homework:''};
const parsed=parseImport('班級,科目,星期,時間,計算類型,學期目標堂數\\n高一 101,物理,2,08:10,段考,\\n探究班,自然探究與實作,,,探究,18','schedule');
assert.equal(parsed.next.classes.length,4);
assert.equal(parsed.next.classes[0].slots[0].day,2);
assert.equal(parsed.next.notes.example.content,'keep');
assert.equal(parsed.next.classes[3].mode,'inquiry');
assert.equal(state.classes[0].slots[0].day,1);
assert.throws(()=>parseImport('班級,科目,星期,時間\\n高一 101,物理,8,09:00','schedule'));
assert.throws(()=>parseImport('日期,名稱,類型\\n2028-01-01,過期,停課','calendar'));
assert.throws(()=>parseImport('日期,名稱,類型\\n2026-11-27,重疊段考,段考1','calendar'));
const calendar=parseImport('日期,結束日期,名稱,類型,班級,時間\\n2026-10-20,2026-10-21,活動,停課,全部,','calendar');
assert.equal(calendar.next.events.length,state.events.length+2);
const roundtrip=JSON.parse(JSON.stringify({active:'original',workspaces:[{id:'original',data:state},{id:'other',data:parsed.next}]}));
roundtrip.workspaces[1].data.notes.example.content='changed';
assert.equal(roundtrip.workspaces[0].data.notes.example.content,'keep');
console.log('PASS: v1 migration; notes preserved; course merge; isolated workspace serialization; invalid imports rejected; multi-day calendar import.');
`,{CalendarEngine:E,addDays:E.addDays,assert,structuredClone,Intl,Date,console,crypto:require('node:crypto').webcrypto});
